// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgdQmM5xjAFwtNk5PN61X2FEX7grg6e94',
    appId: '1:296041546243:web:273e88faf1a7a1abb60436',
    messagingSenderId: '296041546243',
    projectId: 'ctp-job-cards',
    authDomain: 'ctp-job-cards.firebaseapp.com',
    storageBucket: 'ctp-job-cards.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1jSxzKCGDAF605TB-kjxW_2x2ynXrK6Q',
    appId: '1:296041546243:android:eeec36e0f2b509bdb60436',
    messagingSenderId: '296041546243',
    projectId: 'ctp-job-cards',
    storageBucket: 'ctp-job-cards.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKe669DAu6E-e29OB0d11aa9dmY4RH6SQ',
    appId: '1:296041546243:ios:6d0547bca33b2ec9b60436',
    messagingSenderId: '296041546243',
    projectId: 'ctp-job-cards',
    storageBucket: 'ctp-job-cards.firebasestorage.app',
    iosBundleId: 'com.example.ctpJobCards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKe669DAu6E-e29OB0d11aa9dmY4RH6SQ',
    appId: '1:296041546243:ios:6d0547bca33b2ec9b60436',
    messagingSenderId: '296041546243',
    projectId: 'ctp-job-cards',
    storageBucket: 'ctp-job-cards.firebasestorage.app',
    iosBundleId: 'com.example.ctpJobCards',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgdQmM5xjAFwtNk5PN61X2FEX7grg6e94',
    appId: '1:296041546243:web:6f70a1cbb07a909cb60436',
    messagingSenderId: '296041546243',
    projectId: 'ctp-job-cards',
    authDomain: 'ctp-job-cards.firebaseapp.com',
    storageBucket: 'ctp-job-cards.firebasestorage.app',
  );
}
